version: '3'
services:

  wp:
    image: library/wordpress
    links:
      - mysql
    ports:
      - 8091:80
    volumes:
      - ./www:/var/www/html
      - ./logs/apache2:/var/log/apache2
      - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./conf/ports.conf:/etc/apache2/ports.conf
      - ./conf/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./src/plugins:/var/www/html/wp-content/plugins
      - ./src/themes:/var/www/html/wp-content/themes

  mysql:
    image: mysql:8.0.16
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3406:3306
    volumes:
      - ./conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./conf/mysql-init-scripts:/docker-entrypoint-initdb.d

  ftp:
    build:
      context: ./ftp
    ports:
      - 2121:2121
    volumes:
      - ./www:/opt/root/var/www/html
      - ./src/plugins:/opt/root/var/www/html/wp-content/plugins
      - ./src/themes:/opt/root/var/www/html/wp-content/themes
    depends_on:
      - "wp"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
      - /sessions